execute pathogen#infect()
set nocompatible
filetype plugin on
syntax on
set tabstop=2
set softtabstop=0 noexpandtab
set shiftwidth=4
set mouse=a
map q :q<cr>
let g:vimwiki_list = [{'path':'~/Dropbox/vimwiki', 'ext':'.md'}]
map <Leader>wx :! ~/dotfiles/vim/scripts/cleanwiki.sh<cr>
map <Leader>we :! ~/dotfiles/vim/scripts/diary-forward.sh<cr>
map <Leader>t :r! date +"\%Y-\%m-\%d \%H:\%M:\%S"<cr>o
map <Leader>\ :NERDTreeToggle<cr>
map <Leader>db :g/^$/d<cr>
noremap <leader>zz :w !sudo tee % > /dev/null<cr>
au FileType markdown vmap <Leader>ta :EasyAlign*<Bar><Enter>
hi UnwantedTrailerTrash guibg=white ctermbg=white
function! ToggleCalendar()
  execute ":Calendar"
  if exists("g:calendar_open")
    if g:calendar_open == 1
      execute "q"
      unlet g:calendar_open
    else
      g:calendar_open = 1
    end
  else
    let g:calendar_open = 1
  end
endfunction
:autocmd FileType vimwiki map <Leader>wc :call ToggleCalendar()<cr>
